# Generated by Django 5.1.1 on 2024-10-07 07:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('owner', '0004_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='serviceprofile',
            name='service_center_image',
        ),
    ]
