# Generated by Django 5.1.1 on 2024-10-07 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('owner', '0007_alter_serviceprofile_address_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='serviceprofile',
            name='location',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='serviceprofile',
            name='vehicle_make',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
