# Generated by Django 5.1.1 on 2024-10-07 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('owner', '0008_serviceprofile_location_serviceprofile_vehicle_make'),
    ]

    operations = [
        migrations.AddField(
            model_name='serviceprofile',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='uploads/'),
        ),
    ]
