# Generated by Django 5.1.1 on 2024-10-07 11:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('owner', '0009_serviceprofile_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='serviceprofile',
            old_name='image',
            new_name='service_center_image',
        ),
    ]
