# Generated by Django 5.1.1 on 2024-10-06 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0018_teching_sub_alter_improvements_learning'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user_details',
            name='CurrentStatus',
        ),
        migrations.RemoveField(
            model_name='user_details',
            name='Institution',
        ),
        migrations.RemoveField(
            model_name='user_details',
            name='Phone',
        ),
        migrations.RemoveField(
            model_name='user_details',
            name='Qualification',
        ),
        migrations.AlterField(
            model_name='teching',
            name='sub',
            field=models.CharField(default=0, max_length=225),
        ),
    ]
