# Generated by Django 5.1.1 on 2024-10-08 08:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('owner', '0010_rename_image_serviceprofile_service_center_image'),
        ('user', '0025_alter_booking_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='booking',
            name='service_center',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='owner.serviceprofile'),
        ),
    ]
