# Generated by Django 5.1.1 on 2024-10-09 03:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0028_chatmessage'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='bill_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='paid',
            field=models.BooleanField(default=False),
        ),
    ]
