# Generated by Django 5.1.1 on 2024-10-11 06:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0029_booking_bill_amount_booking_paid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feedback',
            name='Comments',
        ),
        migrations.RemoveField(
            model_name='feedback',
            name='Content',
        ),
        migrations.RemoveField(
            model_name='feedback',
            name='Date',
        ),
        migrations.RemoveField(
            model_name='feedback',
            name='Instructor',
        ),
        migrations.RemoveField(
            model_name='feedback',
            name='Material',
        ),
        migrations.RemoveField(
            model_name='feedback',
            name='Overallrating',
        ),
        migrations.RemoveField(
            model_name='feedback',
            name='Rating',
        ),
        migrations.RemoveField(
            model_name='feedback',
            name='levelofteaching',
        ),
        migrations.RemoveField(
            model_name='feedback',
            name='name',
        ),
        migrations.RemoveField(
            model_name='feedback',
            name='user',
        ),
        migrations.AddField(
            model_name='feedback',
            name='booking',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='user.booking'),
        ),
        migrations.AddField(
            model_name='feedback',
            name='completion_timeframe',
            field=models.IntegerField(blank=True, choices=[(1, 'Far Exceeded Timeframe'), (2, 'Exceeded Timeframe'), (3, 'Met Timeframe'), (4, 'Under Timeframe')], null=True),
        ),
        migrations.AddField(
            model_name='feedback',
            name='expectations_met',
            field=models.IntegerField(blank=True, choices=[(1, 'Did Not Meet Expectations'), (2, 'Below Expectations'), (3, 'Met Expectations'), (4, 'Exceeded Expectations')], null=True),
        ),
        migrations.AddField(
            model_name='feedback',
            name='service_quality',
            field=models.IntegerField(blank=True, choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], null=True),
        ),
        migrations.AddField(
            model_name='feedback',
            name='staff_professionalism',
            field=models.CharField(blank=True, choices=[('Very Unprofessional', 'Very Unprofessional'), ('Unprofessional', 'Unprofessional'), ('Neutral', 'Neutral'), ('Professional', 'Professional'), ('Very Professional', 'Very Professional')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='feedback',
            name='suggestions',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='feedback',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
